### ISSUE TITLE
[FEATURE] [BREAKING] Transition Streaming Framework and Plugin to Scala

### ISSUE THREAD

**Issue by s-vitaliy** [SneaksAndData/arcane-stream-sqlserver-change-tracking#136]
### Description

.NET has served its purpose and with the new design on the road that allows having both producer and consumer inside Arcane runner, we need Iceberg API access, which is not a thing in .NET. Thus we now depart from MS world and re-write streaming code in ZIO

### Checklist
- [x] Implement Change Capture interval
- [x] StreamGraphBuilder for backfills
- [x] Parse datetime correctly, see: https://learn.microsoft.com/en-us/power-apps/maker/data-platform/export-data-lake-faq
    - [x] Open question: timzone? 
- [ ] Logs and metrics: https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/issues/142
  - [x] enrich logs with stream id
  - [x] enrich logs with stream kind
  - [x] ~remove logback.xml from arcane.framework~
  - [x] ~snake_case for stream id and stream kind enrichers~
  - [x] ~Implement SneaksAndData/arcane-framework-scala#76~
- [x] SneaksAndData/arcane-stream-sqlserver-change-tracking#94
- [x] Refactor query provider based on comments in SneaksAndData/arcane-stream-sqlserver-change-tracking#75 
- [x] Update CRD model https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/issues/78
- [x] ~Group environment vairables consumed by the pulgin/framework~ it is not needed, for list we can use `.env` files, common file for all env variable names is actually not required.
- [x] ~Refactor StreamGraphBuilder based on comments from https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/pull/77#discussion_r1832370269~
- [x] ~https://github.com/SneaksAndData/arcane-framework-scala/issues/115~
- [x] ~SneaksAndData/arcane-framework-scala#114~
- [x] ~Align java & openjdk & jre & scala versions in all infrastructure.~
- [x] Stream hooks in graph events

**Comment by s-vitaliy** [comment]
Resolved with the commits attached. The metrics task will be resolved in different task.
